/**
 * MSW worker — runs in the browser when VITE is in DEV mode.
 *
 * Started by `main.tsx` before render so the first request to the app is
 * intercepted. The service-worker file itself is generated by running
 * `npm run msw:init` after install.
 */

import { setupWorker } from 'msw/browser';

import { handlers } from './handlers';

export const worker = setupWorker(...handlers);